runners:
  indiclid-bert:
    batching:
      enabled: true
      max_batch_size: 100
      max_latency_ms: 500
  indiclid_ftn:
    batching:
      enabled: true
      max_batch_size: 100
      max_latency_ms: 500
  xlm_roberta_base_language_detection:
    batching:
      enabled: true
      max_batch_size: 100
      max_latency_ms: 500
