runners:
  indiclid-bert:
    batching:
      enabled: true
      max_batch_size: 100
      max_latency_ms: 500
  xlm-roberta-base-language-detection:
    batching:
      enabled: true
      max_batch_size: 100
      max_latency_ms: 500
