IndicLID_lang_code_dict_reverse = {
    0: "asm_Latn",
    1: "ben_Latn",
    2: "brx_Latn",
    3: "guj_Latn",
    4: "hin_Latn",
    5: "kan_Latn",
    6: "kas_Latn",
    7: "kok_Latn",
    8: "mai_Latn",
    9: "mal_Latn",
    10: "mni_Latn",
    11: "mar_Latn",
    12: "nep_Latn",
    13: "ori_Latn",
    14: "pan_Latn",
    15: "san_Latn",
    16: "snd_Latn",
    17: "tam_Latn",
    18: "tel_Latn",
    19: "urd_Latn",
    20: "eng_Latn",
    21: "other",
}
